### ISSUE TITLE
WARNING:kolibri_gnome.globals:Error loading translation file: [Errno 2] No translation file found for domain: 'kolibri-gnome'

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.learningequality.Kolibri#3]
https://github.com/learningequality/kolibri-installer-gnome/issues/2

**Comment by dylanmccall** [comment]
Fixed with this pull request: https://github.com/flathub/org.learningequality.Kolibri/pull/4. A new stable release should appear in a couple hours :)

**Comment by LeandroStanger** [comment]
![Captura de tela de 2020-05-30 08-29-41](https://user-images.githubusercontent.com/26097419/83327103-c9348580-a24f-11ea-99f1-8baeea9eb2f8.png)
